server:
  port: 8088

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:adesso;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      pool-name: adesso
      maximum-pool-size: 10
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # damit aus camelCased Attributen für Postgres passende column-Namen werden
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 

  h2:
    console:
      enabled: true
      path: /h2-console
      
adesso:
  singleProp: val1
  port: 80
  workshop:
    label: Test
    prop2: Value2
    

---
spring:
  profiles: prod

server:
  port: 8090

adesso:
  port: 8080
